server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pravinx29/java-microservices-crud.git
          default-label: main      # branch name
          search-paths: config     # folder inside repo where yml files are
          clone-on-start: true     # clones once when server starts
